---
start_charging:
  name: "Start charging"
  description: "Start a charging session with an optional RFID card ID"
  target:
    entity:
      domain: "switch"
      integration: "evcnet"
  fields:
    card_id:
      name: "RFID Card ID"
      description: "Optional RFID card ID to use for this charging session."
      required: false
      selector:
        text:
    channel_id:
      name: "Channel"
      description: "Optional channel (socket) to use for this charging session."
      required: false
      default: "1"
      example: "2"
      selector:
        select:
          options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
            - "9"
            - "10"
          custom_value: true
          mode: dropdown
